# First order damped system analysis

In [1]:
import numpy as np
from scipy import linalg as la
import matplotlib
import matplotlib.pyplot as plt
matplotlib.rcParams.update({'font.size': 12,'font.family':'serif'})

In [2]:
%matplotlib notebook

## Parameter choices

In [3]:
m = 1
k = 1
c = 0.1

## Construct M, C, K

In [4]:
M = m*np.eye(3)

C = np.zeros((3,3))
C[0,0]=c
C[1,1] = c
C[0,1] = -c
C[1,0] = -c


K = 2*k*np.eye(3)
K += -k*np.diag(np.array([1,1]),1)
K += -k*np.diag(np.array([1,1]),-1)

print('M = ')
print(M)

print('\nC = ')
print(C)

print('\nK = ')
print(K)

M = 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

C = 
[[ 0.1 -0.1  0. ]
 [-0.1  0.1  0. ]
 [ 0.   0.   0. ]]

K = 
[[ 2. -1.  0.]
 [-1.  2. -1.]
 [ 0. -1.  2.]]


## undamped case - second order

In [5]:
wn2,Phi = la.eigh(K,M)  # eigh tells scipy that the matrices are symmetric
wn = np.sqrt(wn2)       # sqrt to get w from w**2
scale_factor = np.max(np.abs(Phi),axis=0) # get max of each column
Phi = Phi/scale_factor  # normalise so numbers easier to interpret

print('wn = ')
print(np.round(wn*100)/100)  # round(*100)/100 to print 2 decimal places

print('\n Phi = ')
print(np.round(Phi*100)/100) # round(*100)/100 to print 2 decimal places

wn = 
[0.77 1.41 1.85]

 Phi = 
[[-0.71 -1.    0.71]
 [-1.    0.   -1.  ]
 [-0.71  1.    0.71]]


## undamped case - first order method

In [6]:
A_undamped = np.block([[np.zeros((3,3)),np.eye(3)],[-np.matmul(la.inv(M),K),-np.matmul(la.inv(M),C)*0]])
print('A_undamped = ')
print(A_undamped)

A_undamped = 
[[ 0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  1.]
 [-2.  1. -0. -0.  0. -0.]
 [ 1. -2.  1.  0. -0. -0.]
 [-0.  1. -2. -0. -0. -0.]]


In [7]:
lambda_A_undamped, Phi_A_undamped = la.eig(A_undamped)
print('Complex lambda from the undamped A matrix = ')
print(np.round(lambda_A_undamped*100)/100)

print('\nImaginary part of complex lambda from the undamped A matrix, wn = ')
wn_A_undamped = np.imag(lambda_A_undamped)
print(np.round(wn_A_undamped*100)/100)

print('\nMode shapes Phi from A (scaled to max of first three rows in each column) = ')
scale_factor = np.max(np.abs(Phi_A_undamped[0:3,:]),axis=0) # get max of each column from first three rows
Phi_A_undamped = Phi_A_undamped/scale_factor  # normalise so numbers easier to interpret
print(np.round(Phi_A_undamped*100)/100)

Complex lambda from the undamped A matrix = 
[0.+1.85j 0.-1.85j 0.+1.41j 0.-1.41j 0.+0.77j 0.-0.77j]

Imaginary part of complex lambda from the undamped A matrix, wn = 
[ 1.85 -1.85  1.41 -1.41  0.77 -0.77]

Mode shapes Phi from A (scaled to max of first three rows in each column) = 
[[ 0.  +0.71j -0.  -0.71j  0.  +1.j   -0.  -1.j   -0.71+0.j   -0.71+0.j  ]
 [-0.  -1.j    0.  +1.j   -0.  +0.j    0.  +0.j   -1.  +0.j   -1.  +0.j  ]
 [ 0.  +0.71j  0.  -0.71j -0.  -1.j    0.  +1.j   -0.71+0.j   -0.71+0.j  ]
 [-1.31+0.j   -1.31+0.j   -1.41+0.j   -1.41+0.j   -0.  -0.54j  0.  +0.54j]
 [ 1.85+0.j    1.85+0.j   -0.  +0.j    0.  +0.j    0.  -0.77j  0.  +0.77j]
 [-1.31+0.j   -1.31+0.j    1.41+0.j    1.41-0.j    0.  -0.54j  0.  +0.54j]]


## damped case - first order method

In [8]:
A = np.block([[np.zeros((3,3)),np.eye(3)],[-np.matmul(la.inv(M),K),-np.matmul(la.inv(M),C)]])
print('A = ')
print(A)

A = 
[[ 0.   0.   0.   1.   0.   0. ]
 [ 0.   0.   0.   0.   1.   0. ]
 [ 0.   0.   0.   0.   0.   1. ]
 [-2.   1.  -0.  -0.1  0.1 -0. ]
 [ 1.  -2.   1.   0.1 -0.1 -0. ]
 [-0.   1.  -2.  -0.  -0.  -0. ]]


In [9]:
lambda_A, Phi_A = la.eig(A)
print('Complex lambda from the **damped** A matrix = ')
print(np.round(lambda_A*100)/100)

print('\nImaginary part of complex lambda from the **damped** A matrix, wn = ')
wn_A = np.imag(lambda_A)
print(np.round(wn_A*100)/100)

print('\nReal part of complex lambda from the **damped** A matrix, sigma = ')
sigma_A = np.real(lambda_A)
print(np.round(sigma_A*1000)/1000)

print('\nComplex mode shapes Phi from the **damped** A matrix (scaled) = ')
scale_factor = np.max(np.abs(Phi_A[0:3,:]),axis=0) # get max of each column from first three rows
Phi_A = Phi_A/scale_factor  # normalise so numbers easier to interpret
print(np.round(Phi_A*100)/100)

Complex lambda from the **damped** A matrix = 
[-0.07+1.84j -0.07-1.84j -0.02+1.42j -0.02-1.42j  0.  +0.77j -0.  -0.77j]

Imaginary part of complex lambda from the **damped** A matrix, wn = 
[ 1.84 -1.84  1.42 -1.42  0.77 -0.77]

Real part of complex lambda from the **damped** A matrix, sigma = 
[-0.073 -0.073 -0.025 -0.025 -0.002 -0.002]

Complex mode shapes Phi from the **damped** A matrix (scaled) = 
[[-0.06+0.72j -0.06-0.72j  0.16+0.98j  0.16-0.98j -0.71-0.02j -0.71+0.02j]
 [-0.04-1.j   -0.04+1.j   -0.07+0.01j -0.07-0.01j -1.  +0.j   -1.  +0.j  ]
 [ 0.16+0.69j  0.16-0.69j -0.02-1.j   -0.02+1.j   -0.71+0.j   -0.71+0.j  ]
 [-1.32-0.16j -1.32+0.16j -1.39+0.2j  -1.39-0.2j   0.01-0.54j  0.01+0.54j]
 [ 1.84+0.j    1.84+0.j   -0.01-0.1j  -0.01+0.1j   0.  -0.77j  0.  +0.77j]
 [-1.28+0.25j -1.28-0.25j  1.42+0.j    1.42+0.j    0.  -0.54j  0.  +0.54j]]


In [10]:
Q = np.imag(lambda_A)/2/np.real(lambda_A)
print(Q)

[ -12.60171137   12.60171137  -28.57391465   28.57391465 -179.17176966
  179.17176966]
